apiVersion: v1
kind: Service
metadata:
  labels:
    service: sca-chat-backend
  name: sca-chat-backend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    service: sca-chat-backend
  type: LoadBalancer