apiVersion: v1
kind: Service
metadata:
  labels:
    service: sca-chat-frontend
  name: sca-chat-frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: sca-chat-frontend
  type: LoadBalancer